### ISSUE TITLE
Problème de téléchargement et de transcription pour certaines pages du corpus

### ISSUE THREAD

**Issue by zoeleveque** [Anahide64/Git-ENC-Kovalewsky-1893#2]
Re-bonjour Anahide et Kate !
Je suis confrontée à un problème sur eScriptorium, et je voulais savoir ce qu'il en était de votre côté. J'ai importé les pages que je devais transcrire sur eScriptorium à partir de Gallica, mais je me suis rendue compte que certains bas de pages étaient coupés. Je n'arrive du coup pas à lire et transcrire les dernières lignes de ces pages. Est-ce que vous avez eu le même problème ?

**Comment by zoeleveque** [comment]
Bonsoir Anahide, j'ai mis un peu de temps à te répondre, j'en suis désolée. Au final, je ne crois pas que c'était un problème de connexion, le problème survenait même quand la connexion était stable. J'ai fini par procéder différemment : au lieu d'importer les pages de Gallica sur eScriptorium en format PDF, je les ai importées au format JPEG. Il a fallu télécharger les pages une par une de nouveau, mais ca a marché, les pages étaient entières. Kate, je ne sais pas si tu as rencontré ce problème, mais au cas où, tu pourras essayer cette technique. Bonne soirée à toutes les deux !

**Comment by Anahide64** [comment]
Super :) alors je clos cette issue.
